name: build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  create:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        platform: [
            android-arm, android-arm64, android-x64, android-x86,
            linux-armv7, linux-arm64, linux-x64, linux-x86,
            windows-x64, windows-x86, darwin-x64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build ${{ matrix.platform }} docker image
        run: make env PLATFORM=${{ matrix.platform }}

      - name: Build libtorrent-go-${{ matrix.platform }}
        run: |
          mkdir tmp
          make ${{ matrix.platform }} GOPATH=tmp

      - name: Push ${{ matrix.platform }} docker image
        if: success() && github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        run: |
          docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
          make push PLATFORM=${{ matrix.platform }}
